main: me.attila.ctf.App
name: CaptureTheFlag
version: 0.1
api-version: 1.15
commands:
   addFlag:
      description: Register flag base location
      usage: /addFlag team_number
   setTeam:
      description: Set own team
      usage: /setTeam team_number